Model builder
Motivation-and-Behaviour/sleepIPD_analysis pull request #22
Opened 2023-01-24 03:15 UTC by conig

Relevant section of the protocol is:

> To examine the relationship between sleep and physical activity (Research Questions 1-2) we will use study fixed-effects to account for the nesting of participants in studies (Curran et al 2009). Fixed-effects (not the same as complete pooling analysis that ignores data nesting) control for all time-invariant between-study variance and will allow us to explore within study associations and moderators. We will nest individuals within days, and days within study. We will examine both main effects and subpopulation effects (using separate models), including the following pre-specified individual-level moderators; age (chronological), body mass index z-score (z transformed), SES, ethnicity, and sex as categorical. Day of the week, season (summer vs winter), geographic location, and daylight length will also be included as moderators because these influence sleep and physical activity. Accelerometer wear location will be included as a moderator. Sleep and physical activity may be temporally related where early morning and late evening physical activity can negatively influence optimum sleep duration and sleep quality. To account for this, we will include the time of the day corresponding to the most active periods of physical activity as a moderator. The most active 60, 30, 15, 10 and 5 minutes within 4 windows of time; midnight to 6am (early), 6am to 12pm (normal), 12pm -6pm (normal), 6pm -midnight (late) will be extracted from GGIR and used to test the effect of physical activity proximity to bedtime and wake time on sleep.

Some of these moderators will need to be specified in the predictors argument. But the fixed component is taken into account in the model:

> We will nest individuals within days, and days within study.

```
+ factor(studyid) + factor(measurementday) + factor(participant_id)
```

We're just estimating fixed effects for each of these variables, there's no nesting order. Let me know if something else was intended.

Note that `"participant_id"` hasn't been made available in `clean_data` yet.

2023-01-24 03:39 UTC, mnoetel requested changes
Are you supposed to add these to function.R?
require(data.table)
require(papaja)

2023-01-24 03:49 UTC, conig commented
Is adding library calls to function.R to make them available everywhere? @mnoetel @tarensanders 
Doesn't calling within a function reduce conflicts? I will yield but want to understand.

2023-01-24 05:24 UTC, conig commented
Have added to packages.R

I also added a function to make prediction slopes off the models `plot_effects_RQ1`

2023-01-24 06:14 UTC, mnoetel approved these changes

2023-01-24 06:14 UTC, mnoetel commented
argh: "This branch has conflicts that must be resolved."

2023-01-24 08:59 UTC, tarensanders commented on renv.lock
> +<<<<<<< HEAD
@conig FYI you have a merge conflict here

2023-01-24 09:50 UTC, conig commented
Thanks, fixed I believe.

2023-01-27 00:01 UTC, tarensanders approved these changes
Looks great to me. Huge amount of work!

2023-01-27 00:01 UTC, tarensanders commented on R/make_model_list.R
> +    "sleep_duration" = c("pa_volume * age + I(pa_volume^2) * age"),
Is there a reason sleep_duration is the only one fit with the quadratic?
Should the instructions have a linear and a quadratic for each?

2023-01-27 00:01 UTC, tarensanders commented on R/make_table1.R
> -    sleep_regularity,# sleep_onset_time, sleep_wakeup_time,
lol did you touch this file just to delete whitespace?

2023-01-27 00:01 UTC, tarensanders commented on _targets.R
> +plan("multisession")
Any reason to prefer this to 
```R
library(future.callr)
plan(callr)
```
Legit asking - I don't know that it would matter, it's just what I've used because [Landau recommends it](https://books.ropensci.org/targets/hpc.html#future-locally)

2023-01-27 00:05 UTC, conig commented on R/make_model_list.R
> +    "sleep_duration" = c("pa_volume * age + I(pa_volume^2) * age"),
Yeah that was just for testing. About to commit the full list. Using expand.grid.

2023-01-27 00:07 UTC, conig commented on R/make_table1.R
> -    sleep_regularity,# sleep_onset_time, sleep_wakeup_time,
Haha nah, been doing endless merge conflict resolutions. Probably happened as part of that. At one point a var was crashing imps so I took it out so I could keep working.

2023-01-27 00:07 UTC, conig commented on _targets.R
> +plan("multisession")
I don't know what future.callr does. I got mine off a targets tute ages ago. Lets you use tar_make_future(workers = n) explicitly.

2023-01-27 00:09 UTC, tarensanders commented on _targets.R
> +plan("multisession")
Yeah, the targets book doesn't say why callr is recommended. Multisession seems to run fine for me.

2023-01-27 04:04 UTC, tarensanders approved these changes

2023-01-27 04:04 UTC, merged